app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    
user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    
admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

fos_user:
    resource: "@UserBundle/Resources/config/routing.yml"